disabled_rules:
  - multiple_closures_with_trailing_closure
  - nesting
  - identifier_name
  - type_name
  - operator_usage_whitespace 
opt_in_rules:
  - anyobject_protocol
  - closure_spacing
  - closure_end_indentation
  - closure_parameter_position
  - collection_alignment
  - contains_over_first_not_nil
  - discouraged_object_literal
  - empty_xctest_method
  - empty_string
  - explicit_init
  - fatal_error_message
  - first_where
  - function_parameter_count
  - last_where
  - multiline_parameters
  - overridden_super_call
  - private_action
  - private_outlet
  - prohibited_super_call
  - prohibited_interface_builder
  - quick_discouraged_focused_test
  - sorted_first_last
  - trailing_whitespace
  - todo
  - unused_import
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition
  - xct_specific_matcher
excluded:
  - .build
  - Carthage
  - Pods

# Configurable Rules
identifier_name:
  min_length: # only min_length
    error: 3 # only error
  excluded: # excluded via string array
    - id
    - vc
    - URL
    - GlobalAPIKey
    - qa
    - uat
    - rx
vertical_whitespace:
  max_empty_lines: 2
function_body_length:
  warning: 400
line_length:
  warning: 160
  ignores_comments: true
overridden_super_call:
  excluded:
    - setUp()
    - tearDown()