osx_image: xcode11.1
language: swift
before_install:
  - make install
  - make xcodeproj
  - carthage update --platform iOS

install:
  - bundle install

# run tests
script:
  - make test

# upload codecov report
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'plop-ios'
